name: yobi
description: Yobi desktop app

version: 0.9.94+104

publish_to: none
environment:
  sdk: ">=2.6.0 <3.0.0"
  # The testbed interacts with build scripts on the Flutter side that are not
  # yet stable, so it requires a very recent version of Flutter.
  # This version will increase regularly as the build scripts change.
  flutter: ">=1.12.13"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.5.12+4
  badges: ^1.2.0
  # sentry_flutter: ^4.0.6 // recurrent error Failed to save envelope: MissingPluginException...
  #cupertino_icons: ^0.1.0
  #charts_flutter: ^0.11.0
  charts_flutter:
    git:
      url: git://github.com/google/charts.git
      path: charts_flutter
  collection: ^1.14.11
  cross_connectivity: ^2.0.1
  crypto: ">=2.1.5"
  csv: ^4.1.0
  encrypt: ">=4.0.3"
  expand_widget: ^1.2.0+1 # this is not nedded hardcode please
  flare_flutter: ^2.0.6
  flutter_mobx: ^1.1.0+2
  flutter_markdown: ^0.5.2
  #flutter_phoenix: ^0.1.0
  #flutter_screenutil: ^1.0.2
  #flutter_svg: ^0.18.0
  font_awesome_flutter: ^8.12.0
  google_fonts: ^1.1.2
  intl: ^0.17.0
  json_annotation: ^3.1.1 # use class generator instead of this please
  mobx: ^1.2.1+4
  path_provider: ^1.6.28
  provider: ^4.3.3
  path: ^1.6.4
  sembast: ^3.0.2
  spreadsheet_decoder: ^1.2.0
  package_info: ^0.4.0+16
  pdf: ^1.13.0
  printing: ^3.7.2
  uuid: ^2.2.2
  rc_router: ^0.3.0 #upgrade to 0.3.0
  settings_ui: ^0.3.0 # remove and hardcode this please
  #twilio_flutter: ^0.0.5  # R&D should not be implemented until 
  #audioplayers: ^0.15.1
  file_picker_cross: ^4.2.8
  sortedmap: ^0.5.1

#  file_chooser:
#    git:
#      url: git://github.com/google/flutter-desktop-embedding.git
#      path: plugins/file_chooser
#      ref: 2b9353a

dev_dependencies:
  flutter_test:
      sdk: flutter
  build_runner: ^1.11.5
  mobx_codegen: ^1.1.2
  json_serializable: ^3.5.1

flutter:
  uses-material-design: true
    

  # See https://github.com/flutter/flutter/wiki/Desktop-shells#fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900

     
    
